apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  namespace: registry-internal
spec:
  storageClassName: manual
  volumeName: registry-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi