apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data-claim
spec:
  storageClassName: manual
  volumeName: database-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi