apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data-pvc
  namespace: database
spec:
  storageClassName: manual
  volumeName: database-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi