services:
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: seaport
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seaport_app
volumes:
  pg_data: {}