apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaport-deployment
  namespace: seaport
  labels:
    app: seaport
spec:
  replicas: 0
  selector:
    matchLabels:
      app: seaport
  template:
    metadata:
      labels:
        app: seaport
    spec:
      serviceAccountName: seaport-admin
      containers:
        - name: seaport-container
          image: internal.io/seaport:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: JAR_ARGS
              value: "-D#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://internal-ingress-service/sso/realms/main/protocol/openid-connect/certs"
#          JAR_ARGS