server = "http://registry-service.internal-registry.svc.cluster.local"

[host."http://registry-service.internal-registry.svc.cluster.local"]
capabilities = ["pull", "resolve", "push"]
skip_verify = true