apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sso-data-pvc
  namespace: sso
spec:
  storageClassName: manual
  volumeName: sso-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi